use std::{env, fs, io, path::PathBuf};

const DEFAULT_MAX_CHILDREN: usize = 32;

fn main() -> io::Result<()> {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-env-changed=FLATBT_MAX_CHILDREN");

    let max_children = match env::var_os("FLATBT_MAX_CHILDREN") {
        None => DEFAULT_MAX_CHILDREN,
        Some(value) => value
            .to_str()
            .and_then(|value| value.parse::<usize>().ok())
            .ok_or_else(|| {
                io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "FLATBT_MAX_CHILDREN must be a non-negative integer (for example, 64)",
                )
            })?,
    };

    // Stable macro_rules cannot form identifiers from integer tokens.
    // Generate only its input list; the implementation stays in src/children.rs.
    let entries = (0..max_children)
        .map(|index| format!("State{} {index} N{index} Child{index}", index + 1))
        .collect::<Vec<_>>()
        .join(",\n");
    let output = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo sets OUT_DIR"));
    fs::write(
        output.join("tuple_children.rs"),
        format!("// Generated by build.rs.\ntuple_children!(@generate_prefix []\n{entries}\n);\n"),
    )?;

    // Supply literal indices to choose! without a separate hardcoded arity limit.
    let indices = (0..max_children)
        .map(|index| index.to_string())
        .collect::<Vec<_>>()
        .join(" ");
    fs::write(
        output.join("choose_indices.rs"),
        format!(
            "// Generated by build.rs.\n\
             #[doc(hidden)]\n\
             #[macro_export]\n\
             macro_rules! __flatbt_choose_indices {{\n\
                 ($($args:tt)*) => {{\n\
                     $crate::choose!(@arms [{indices}] $($args)*)\n\
                 }};\n\
             }}\n"
        ),
    )
}
