use flatbt::scope::{bind, compute, no_params, read, scope, write};
use flatbt::{BtState, EntryMode, NodeResult, action, seq, update};

#[path = "support/scoped_params.rs"]
mod support;
#[path = "support/wait_frames.rs"]
mod wait;
use support::*;

fn main() {
    fn get_visible_door_pos(world: &mut World) -> Vector2 {
        world.selections += 1;
        world.visible_door
    }
    // These fields are generated by scope! in the companion example.
    #[derive(Default)]
    struct Locals {
        walk_pos: Option<Vector2>,
        door_pos: Option<Vector2>,
    }

    let tree = scope::<Locals, _>(seq((
        // The outer sequence runs initializers once before entering the body.
        bind(
            compute(|world: &mut World| {
                world.selections += 1;
                world.next_patrol
            }),
            write(|locals: &mut Locals| &mut locals.walk_pos),
        ),
        bind(
            compute(get_visible_door_pos),
            write(|locals: &mut Locals| &mut locals.door_pos),
        ),
        // This inner sequence corresponds to the explicit sequence body.
        seq((
            bind(LookAt, read(|locals: &Locals| locals.door_pos.as_ref())),
            no_params(wait::wait_frames(1)),
            bind(
                action(Walk),
                read(|locals: &Locals| locals.walk_pos.as_ref()),
            ),
        )),
    )));
    let mut state = BtState::new(&tree);
    let mut world = World {
        next_patrol: Vector2(10.0, 20.0),
        visible_door: Vector2(90.0, 80.0),
        looked_at: Vec::new(),
        walked_to: Vec::new(),
        selections: 0,
    };
    assert_eq!(
        update(&tree, &mut state, &mut world, EntryMode::Resume),
        NodeResult::Running
    );
    // Initializers ran once. Their values survive changes to the world.
    world.next_patrol = Vector2(-1.0, -1.0);
    assert_eq!(
        update(&tree, &mut state, &mut world, EntryMode::Evaluate),
        NodeResult::Running
    );
    assert_eq!(
        update(&tree, &mut state, &mut world, EntryMode::Resume),
        NodeResult::Success
    );
    assert_eq!(world.selections, 2);
    assert_eq!(world.looked_at, [Vector2(90.0, 80.0)]);
    assert_eq!(world.walked_to, [Vector2(10.0, 20.0)]);
    println!(
        "Looked at {:?}; walked to {:?}",
        world.looked_at, world.walked_to
    );
}
