use std::{env, fs, io, path::PathBuf};

const DEFAULT_MAX_CHILDREN: usize = 32;
const DEFAULT_MAX_PARAMS: usize = 32;

fn configured_limit(name: &str, default: usize) -> io::Result<usize> {
    println!("cargo::rerun-if-env-changed={name}");
    match env::var_os(name) {
        None => Ok(default),
        Some(value) => value
            .to_str()
            .and_then(|value| value.parse::<usize>().ok())
            .ok_or_else(|| {
                io::Error::new(
                    io::ErrorKind::InvalidInput,
                    format!("{name} must be a non-negative integer (for example, 64)"),
                )
            }),
    }
}

fn main() -> io::Result<()> {
    println!("cargo::rerun-if-changed=build.rs");
    let max_children = configured_limit("FLATBT_MAX_CHILDREN", DEFAULT_MAX_CHILDREN)?;
    let max_params = configured_limit("FLATBT_MAX_PARAMS", DEFAULT_MAX_PARAMS)?;

    // Stable macro_rules cannot form identifiers from integer tokens.
    // Generate only its input list; the implementation stays in src/composition/children.rs.
    let entries = (0..max_children)
        .map(|index| format!("State{} {index} N{index} Child{index}", index + 1))
        .collect::<Vec<_>>()
        .join(",\n");
    let output = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo sets OUT_DIR"));
    fs::write(
        output.join("tuple_children.rs"),
        format!("// Generated by build.rs.\ntuple_children!(@generate_prefix []\n{entries}\n);\n"),
    )?;

    // Let downstream macros share the tuple limit without duplicating build settings.
    let indices = (0..max_children)
        .map(|index| index.to_string())
        .collect::<Vec<_>>()
        .join(" ");
    fs::write(
        output.join("child_indices.rs"),
        format!(
            "// Generated by build.rs.\n\
             #[doc(hidden)]\n\
             #[macro_export]\n\
             macro_rules! __flatbt_child_indices {{\n\
                 ([$($callback:tt)+]; $($args:tt)*) => {{\n\
                     $($callback)+!([{indices}] $($args)*)\n\
                 }};\n\
             }}\n"
        ),
    )?;

    let params = (0..max_params)
        .map(|index| format!("P{index}"))
        .collect::<Vec<_>>()
        .join(", ");
    fs::write(
        output.join("tuple_params.rs"),
        format!("// Generated by build.rs.\ntuple_param_shapes!(@prefix []; {params});\n"),
    )
}
